server:
  port: 8080

spring:
  config:
    activate:
      on-profile: qa

---

spring:
  profile: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Vicky@10
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: '"Welcome to Daily Code Buffer!!"'

---
spring:
  profile: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Vicky@10
    url: jdbc:mysql://localhost:3306/dcbapp_qa
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: '"Welcome to Daily Code Buffer!!"'

---
spring:
  profile: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Vicky@10
    url: jdbc:mysql://localhost:3306/dcbapp_prod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: '"Welcome to Daily Code Buffer!!"'